menu:
  主页: /
  归档: /archives

logo: Victor Zhang

more:
  Github: https://github.com/VictorZhang2014
  Facebook: https://www.facebook.com/victor.john.92167789
  知乎: https://www.zhihu.com/people/victor-48-5/activities
  CSDN: http://blog.csdn.net/u013538542

about:
  title: Theme Pln
  link: https://github.com/gaoryrt/hexo-theme-pln

disqus_shortname: 

excerpt_num: 120

footer_info: © Victor Zhang 2014-2018